apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-instrumentation-nodejs
  namespace: newrelic
spec:
  agent:
    language: nodejs
    image: newrelic/newrelic-node-init:latest
    env:
    - name: NEW_RELIC_CLOUD_AWS_ACCOUNT_ID
      value: {{ .Values.awsAccountId | quote }}
    - name: NEW_RELIC_LOG_ENABLED
      value: "true"
    - name: NEW_RELIC_LOG_LEVEL
      value: "info"
    - name: NEW_RELIC_LOG
      value: "stdout"
  podLabelSelector:
    matchExpressions:
      - key: "app.kubernetes.io/name"
        operator: "In"
        values: ["express-app"]
